# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arguments.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='arguments.proto',
  package='recipe_engine',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x61rguments.proto\x12\rrecipe_engine\"\xf4\x01\n\tArguments\x12\x42\n\x10\x61nnotation_flags\x18\x02 \x01(\x0b\x32(.recipe_engine.Arguments.AnnotationFlags\x12:\n\x0c\x65ngine_flags\x18\x04 \x01(\x0b\x32$.recipe_engine.Arguments.EngineFlags\x1a\x38\n\x0f\x41nnotationFlags\x12\x1f\n\x17\x65mit_initial_properties\x18\x02 \x01(\x08J\x04\x08\x01\x10\x02\x1a\'\n\x0b\x45ngineFlags\x12\x18\n\x10use_result_proto\x18\x01 \x01(\x08J\x04\x08\x01\x10\x02\x62\x06proto3')
)




_ARGUMENTS_ANNOTATIONFLAGS = _descriptor.Descriptor(
  name='AnnotationFlags',
  full_name='recipe_engine.Arguments.AnnotationFlags',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emit_initial_properties', full_name='recipe_engine.Arguments.AnnotationFlags.emit_initial_properties', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=232,
)

_ARGUMENTS_ENGINEFLAGS = _descriptor.Descriptor(
  name='EngineFlags',
  full_name='recipe_engine.Arguments.EngineFlags',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_result_proto', full_name='recipe_engine.Arguments.EngineFlags.use_result_proto', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=273,
)

_ARGUMENTS = _descriptor.Descriptor(
  name='Arguments',
  full_name='recipe_engine.Arguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='annotation_flags', full_name='recipe_engine.Arguments.annotation_flags', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_flags', full_name='recipe_engine.Arguments.engine_flags', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ARGUMENTS_ANNOTATIONFLAGS, _ARGUMENTS_ENGINEFLAGS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=279,
)

_ARGUMENTS_ANNOTATIONFLAGS.containing_type = _ARGUMENTS
_ARGUMENTS_ENGINEFLAGS.containing_type = _ARGUMENTS
_ARGUMENTS.fields_by_name['annotation_flags'].message_type = _ARGUMENTS_ANNOTATIONFLAGS
_ARGUMENTS.fields_by_name['engine_flags'].message_type = _ARGUMENTS_ENGINEFLAGS
DESCRIPTOR.message_types_by_name['Arguments'] = _ARGUMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Arguments = _reflection.GeneratedProtocolMessageType('Arguments', (_message.Message,), dict(

  AnnotationFlags = _reflection.GeneratedProtocolMessageType('AnnotationFlags', (_message.Message,), dict(
    DESCRIPTOR = _ARGUMENTS_ANNOTATIONFLAGS,
    __module__ = 'arguments_pb2'
    # @@protoc_insertion_point(class_scope:recipe_engine.Arguments.AnnotationFlags)
    ))
  ,

  EngineFlags = _reflection.GeneratedProtocolMessageType('EngineFlags', (_message.Message,), dict(
    DESCRIPTOR = _ARGUMENTS_ENGINEFLAGS,
    __module__ = 'arguments_pb2'
    # @@protoc_insertion_point(class_scope:recipe_engine.Arguments.EngineFlags)
    ))
  ,
  DESCRIPTOR = _ARGUMENTS,
  __module__ = 'arguments_pb2'
  # @@protoc_insertion_point(class_scope:recipe_engine.Arguments)
  ))
_sym_db.RegisterMessage(Arguments)
_sym_db.RegisterMessage(Arguments.AnnotationFlags)
_sym_db.RegisterMessage(Arguments.EngineFlags)


# @@protoc_insertion_point(module_scope)
