# vpython VirtualEnv installation package for Recipe Engine.

requires-python = '>=3.11,<3.12'
dependencies = [
  'coverage==7.3.1',
  'six==1.15.0',
  'requests==2.31.0',
  'chardet==4.0.0',
  'charset-normalizer==2.0.4',
  'idna==2.8',
  'urllib3==1.26.4',
  'certifi==2020.4.5.1',

  # NOTE: This MUST have a matching version of:
  #  infra/3pp/tools/protoc/${{platform}}
  'protobuf==7.35.1',

  'astunparse==1.6.3',
  'attrs==23.1.0',

  ## Gevent
  'gevent==23.9.1',
  'greenlet==3.0.1',
  'zope-event==5.0',
  'zope-interface==6.0',
  # This is only required on the windows version of gevent.
  "cffi==1.15.1; sys_platform == 'win32' and (platform_machine == 'AMD64' or platform_machine == 'x86_64')",
  # This is only required for cffi.
  "pycparser==2.21; sys_platform == 'win32' and (platform_machine == 'AMD64' or platform_machine == 'x86_64')",

  'psutil==5.8.0+chromium.3',
  'pympler==0.8',
  'future==0.18.2',
  'parameterized==0.8.1',
  'packaging==23.0',
  'packaging-legacy==23.0',
  'googleapis-common-protos==1.75.1',
  'grpcio-status==1.81.1',
  'grpcio==1.81.1',
  'typing-extensions==4.15.0',

  # All pycharm-specific wheels follow:
  'pydevd-pycharm==232.6734.4'
]
