#!/usr/bin/env vpython
# Copyright 2019 The LUCI Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

"""Automatically updates the .proto files in this directory."""

import json
import os
import tarfile

import requests

BASE_URL = 'https://chromium.googlesource.com/infra/luci/luci-go'
SUB_PATH = 'buildbucket/proto'
LOG_URL = BASE_URL+'/+log/master/'+SUB_PATH+'?format=JSON&n=1'
TAR_URL = BASE_URL+'/+archive/%s/'+SUB_PATH+'.tar.gz'

def main():
  """Automatically updates the .proto files in this directory."""
  os.chdir(os.path.abspath(os.path.dirname(__file__)))

  resp = requests.get(LOG_URL)
  commit = str(json.loads(resp.text[4:])['log'][0]['commit'])

  print 'Updating to %r' % (commit,)
  resp = requests.get(TAR_URL % commit, stream=True).raw
  with tarfile.open(mode='r|*', fileobj=resp) as tar:
    for item in tar:
      if item.name.endswith('_config.proto'):
        print 'Skipping %r' % item.name
        continue
      if item.name.endswith('.proto'):
        print 'Extracting %r' % item.name
        tar.extract(item, '.')

  with open('README.md', 'w') as rmd:
    print >> rmd, '// Generated by update.py. DO NOT EDIT.'
    print >> rmd, 'These protos were copied from:'
    print >> rmd, BASE_URL+'/+/'+commit+'/'+SUB_PATH

  print 'Done.'


if __name__ == '__main__':
  main()
