// Code generated by protoc-gen-go.
// source: package.proto
// DO NOT EDIT!

/*
Package recipe_engine is a generated protocol buffer package.

It is generated from these files:
	package.proto

It has these top-level messages:
	DepSpec
	Package
*/
package recipe_engine

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type DepSpec struct {
	ProjectId *string `protobuf:"bytes,1,opt,name=project_id" json:"project_id,omitempty"`
	Url       *string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Branch    *string `protobuf:"bytes,3,opt,name=branch" json:"branch,omitempty"`
	Revision  *string `protobuf:"bytes,4,opt,name=revision" json:"revision,omitempty"`
	// Treat a subtree of a repo as a whole repo unto itself.
	PathOverride     *string `protobuf:"bytes,5,opt,name=path_override" json:"path_override,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DepSpec) Reset()         { *m = DepSpec{} }
func (m *DepSpec) String() string { return proto.CompactTextString(m) }
func (*DepSpec) ProtoMessage()    {}

func (m *DepSpec) GetProjectId() string {
	if m != nil && m.ProjectId != nil {
		return *m.ProjectId
	}
	return ""
}

func (m *DepSpec) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *DepSpec) GetBranch() string {
	if m != nil && m.Branch != nil {
		return *m.Branch
	}
	return ""
}

func (m *DepSpec) GetRevision() string {
	if m != nil && m.Revision != nil {
		return *m.Revision
	}
	return ""
}

func (m *DepSpec) GetPathOverride() string {
	if m != nil && m.PathOverride != nil {
		return *m.PathOverride
	}
	return ""
}

type Package struct {
	ApiVersion       *int32     `protobuf:"varint,1,opt,name=api_version" json:"api_version,omitempty"`
	ProjectId        *string    `protobuf:"bytes,2,opt,name=project_id" json:"project_id,omitempty"`
	RecipesPath      *string    `protobuf:"bytes,3,opt,name=recipes_path" json:"recipes_path,omitempty"`
	Deps             []*DepSpec `protobuf:"bytes,4,rep,name=deps" json:"deps,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}

func (m *Package) GetApiVersion() int32 {
	if m != nil && m.ApiVersion != nil {
		return *m.ApiVersion
	}
	return 0
}

func (m *Package) GetProjectId() string {
	if m != nil && m.ProjectId != nil {
		return *m.ProjectId
	}
	return ""
}

func (m *Package) GetRecipesPath() string {
	if m != nil && m.RecipesPath != nil {
		return *m.RecipesPath
	}
	return ""
}

func (m *Package) GetDeps() []*DepSpec {
	if m != nil {
		return m.Deps
	}
	return nil
}

func init() {
}
