#!/usr/bin/env vpython3
# Copyright 2019 The LUCI Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

"""Automatically updates the .proto files in this directory.

This is not necessarily used for all proto files in this directory;
but should update those listed in SUB_PATHS.
"""

import json
import os
import tarfile

from pathlib import Path

import requests

BASE_URL = 'https://chromium.googlesource.com/infra/turboci/proto'
LOG_URL = BASE_URL+'/+log/main/%s?format=JSON&n=1'
TAR_URL = BASE_URL+'/+archive/%s/%s.tar.gz'

REPO_PATH = 'turboci'

def main():
  """Automatically updates the .proto files in this directory."""
  base_dir = Path(__file__).parent

  to_remove = set()
  for root, _, files in os.walk(base_dir):
    for file in files:
      if file.endswith('.proto'):
        to_remove.add(Path(root) / file)

  resp = requests.get(LOG_URL % (REPO_PATH,))
  commit = str(json.loads(resp.text[4:])['log'][0]['commit'])
  print('Updating to %r' % (commit,))

  resp = requests.get(TAR_URL % (commit, REPO_PATH), stream=True).raw
  with tarfile.open(mode='r|*', fileobj=resp) as tar:
    for item in tar:
      if item.name.endswith('_test.proto'):
        print('Skipping %r' % item.name)
        continue
      if 'internal' in item.name or 'googleapis' in item.name:
        print('Skipping %r' % item.name)
        continue
      if item.name.endswith('.proto'):
        print('Extracting %r' % item.name)
        tar.extract(item, path=base_dir)
        to_remove.discard(base_dir / item.name)

  if to_remove:
    print('Removing stale proto')
    for file in to_remove:
      os.remove(file)

  with open(base_dir /  'README.md', 'w') as rmd:
    print('// Generated by update.py. DO NOT EDIT.', file=rmd)
    print('These protos were copied from:', file=rmd)
    print(BASE_URL+'/+/'+commit+'/'+REPO_PATH, file=rmd)

  print('Done.')


if __name__ == '__main__':
  main()
